//UTIL
export const GET_UTILS = 'GET_UTILS';

//CATEGORY
export const GET_CATEGORIES = 'GET_CATEGORIES';

//FILTER - ALL CONTENT
export const SET_FILTER = 'SET_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const GET_ALL_CONTENT = 'GET_ALL_CONTENT';

//LAST ADDED
export const GET_LAST_ADDED = 'GET_LAST_ADDED';

//POPULAR
export const GET_POPULAR = 'GET_POPULAR';